AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cloud configuration file for CEG 3120.  This template will build two Ubuntu servers per project package needs.
Parameters:
  UbuntuInstanceType:
    Description: Ubuntu Server instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: ' The IP address range that can be used to access the EC2 instance'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    # could restrict to home (note this is just SSH)
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings:
  AWSInstanceType2Arch:  # Supported architectures (x64bit only)
    t2.micro:
      Arch: HVM64
  AWSRegionUbuntu: # AMI for Ubuntu server in each supported region 
    us-east-1:   # N. Virginia
      PV64: NOT_SUPPORTED
      #TODO: is this the AMI we want?
      HVM64: ami-06c1d7addb12a814e
      HVMG2: NOT_SUPPORTED
    us-east-2:   # Ohio
      PV64: NOT_SUPPORTED
      HVM64: NOT_SUPPORTED
      HVMG2: NOT_SUPPORTED
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG 3120 VPC
  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG 3120 VPC
  # Have not messed with route tables / gateways before.
  # Look to see if anything unique, else move to next
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  Route:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  SubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable
  # will also have 2 servers, keeping naming convention here
  Ubuntu1IPAddress:
    Type: 'AWS::EC2::EIP'
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      InstanceId: !Ref Ubuntu1Instance
  #Ubuntu2IPAddress:
  #  Type: 'AWS::EC2::EIP'
  #  DependsOn: AttachGateway
  #  Properties:
  #    Domain: vpc
  #    InstanceId: !Ref Ubuntu2Instance
  #WS19IPAddress:
  #  Type: 'AWS::EC2::EIP'
  #  DependsOn: AttachGateway
  #  Properties:
  #    Domain: vpc
  #    InstanceId: !Ref WS19Instance
  # TODO: Setup the security groups needed by our machines
  # SSH, LDAP, HTTP, HTTPS
  LinuxSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable SSH access via port 22 and open ports 1025 through 2048.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          # May be wise to go back to top where SSHLocation "variable" was made
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          # TODO: only leave ones we need.  What submet is this?
          CidrIp: 130.108.0.0/16  # WSU CIDR
        - IpProtocol: tcp
          FromPort: '1025'
          ToPort: '2048'
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: '1025'
          ToPort: '2048'
          CidrIp: 130.108.0.0/16  # WSU CIDR
        - IpProtocol: -1
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: 10.0.0.0/16
  Ubuntu1Instance:
    Type: 'AWS::EC2::Instance'
    DependsOn: AttachGateway
    Properties:
      ImageId: !FindInMap 
        - AWSRegionUbuntu
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref UbuntuInstanceType
          - Arch
      InstanceType: !Ref UbuntuInstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG 3400 Ubuntu 1
      NetworkInterfaces:
        - GroupSet:
            - !Ref LinuxSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref Subnet
          PrivateIpAddress: 10.0.0.20
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update && \
            # reference web solution here to get a silent install working
            apt-get install -y \
              python \
              nmap \
              vim \
              git \
              wget \
              python3-dev \
              ldap-utils && \
              haproxy && \
            
            # settings for HAProxy
            echo '"frontend http_front", "'\t'bind *:80", "'\t'stats uri /haproxy?stats", "'\t'default_backend http_back","backend http_back","'\t'balance roundrobin","'\t'server Ubuntu2Instance 10.0.0.20:80 check", "'\t'server Ubuntu3Instance 10.0.0.25:80 check", "backend blog_back", "'\t'server Ubuntu2Instance 10.0.0.20:80 check", "'\t'server Ubuntu3Instance 10.0.0.25:80"' > /etc/haproxy/haproxy.cfg && \
            echo "OMG this worked" >> /home/ubuntu/hello.txt && \
            echo "Hello World" >> /etc/skel/default.txt && \ 
            echo "open-server MIIEowIBAAKCAQEAqVH3xUsrVHqkMzxe/7ALZiw74oDXaAuYksqEwNEPH2x67dwiEtqfaNebTNwEVuko85z9wv3dN7SP+jIJrbBNSyo777ONAJAUUKL8X25WREfZQUYW18AfsHDxwWNhj17xJbZvBM/mfL0y6+eukPhlOPpJEcCVooxDx/8geRio13LkgVz32Fgn3EbWHG2+joC8jcJ37uKG+D5KMHAVCCLeexiqCYPvXSbl972dYVOnIgvz7veuNeQVWdTLTFEJJHzo5TkP9a7OkZqvl0yvRpvuPEACDIpXw8tbGWVnQwNaULDdnUxerGc8j6MoZIPNkirWdsobJwqs+VFLnNVbABKaBQIDAQABAoIBACcytq2SDWHtUn4aB9QhqUHqE6MIONX5eUTiZYFN5LZdosfWIn1C54yZ/XX5qXeFWtmrCoRNyRzQTFSbqOnw2rP//wgrBQWQVWOll89v98Cu8XjPBRLFg5CRVSZ0H23ViPY2GdV/W9ic5GEArcUZ/DUInEnjz8BlwHtYcOgX8V6O9cYzAZ5T+SIpErk3rg0x/qyuYDNhk5OXVOANOdr1fZyNGn5Ml5UYLDzzMjtB5f1SVj5cDiaV/eWy3RtyV3x0hrEg2hlwW4bXoB1GyyU36AENhDLdrMCHiaHUMJBk8sf3GS536rgGGwyGHkeo6Oy76JRsy+dv2MgineISeojWjIECgYEA5Va5LzlDMwHpmEQCp2KAIfChCUu6NUlYu25Uf3LT0UoZ2ol7Q6gFVcbuGbx/3UYnnPuLyR30rAh0Ihl34H8PjaR522gBxiyys6NUvC50XnG8BUAebyMGOvdWMhp64TekYthWxBmK5HG3/9uXDvciUjhaRzYYokDF3s1f9tdC0U0CgYEAvQENE1A5NYrjVbL8ngH0HrgtblZ0q8Qs4730ipQsJe1BGsO+mXS/RXUOKUwSd95Q8VzObPq1XAbrlMbegjq4jsoaMtPTsJl/Ug777K6t60uJOxZ/N9PKJqgjApiuNyRbFtqJ3YcJG4gQoxJai57vDLVnQDIUhuhoOi3f87pgD5kCgYEA2wP+J/4ckcrCxZo1mpqz2TXO5GzAcIESTzTnVytW4+lLVWu0HwGHzsoCuutMhQmpbP7BGRkVf3E3TxVZaTiOpusrQIBMKXCoXGuf0XLfyQ3+zFjWd7ZQDeIFHCYzsX+M6qTF/9KQ1OdRG/Qeh7k1uqV8ecNMtS78iHFDsx0R/4UCgYAsepXYKLX96ryLS371tGH95LwUTlZQoe8qfWaSQkKNfmMm6E/vjzEAKIb3owZpnTERTBTsQqfxi1NfhNmSbj1GpTs7IOydj9INvqb80TLuv60A8c9olPfq1wC+OK4vHegt3ao6LvAuwXug1M3oM7PwGrS8v8xi30jAAFHG6uJ2aQKBgHqOvV8bHiWzEHTi70PhJJx3Sna6PwXnVcfo+i682RIoSWy9CCp09PrRDqPZUSfbKlgQz9fIqGkaniBhZX/ridBhkiytiaqcMT1rnUpX9BjD4gmfFtMHSqCLI+68Vrk78qogdGNNngGjD3BpxjPQQw70I4s7VntRm8oYS3J29rdg== server-keys" >> /home/ubuntu/.ssh/authorized_keys && \
            reboot
            
  Ubuntu2Instance:
    Type: 'AWS::EC2::Instance'
    DependsOn: AttachGateway
    Properties:
      ImageId: !FindInMap 
        - AWSRegionUbuntu
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref UbuntuInstanceType
          - Arch
      InstanceType: !Ref UbuntuInstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG 3400 Ubuntu 2
      NetworkInterfaces:
        - GroupSet:
            - !Ref LinuxSecurityGroup
          #AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          #DeleteOnTermination: 'true'
          SubnetId: !Ref Subnet
          PrivateIpAddress: 10.0.0.20
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update && \
            apt-get install -y \
              python \
              nmap \
              vim \
              git \
              wget \
              python3-dev && \
              apache2 && \
              wget https://raw.githubusercontent.com/daniellcurto/Project2/main/Project2-3/index-serv1.html?token=AQXGFYBJML4JATWD7XQH6GC7Z75NW /home/ubuntu/ && \
              cp index-serv1.html /var/wwww/html/index.html && \
            reboot

  Ubuntu3Instance:
    Type: 'AWS::EC2::Instance'
    DependsOn: AttachGateway
    Properties:
      ImageId: !FindInMap 
        - AWSRegionUbuntu
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref UbuntuInstanceType
          - Arch
      InstanceType: !Ref UbuntuInstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG 3400 Ubuntu 3
      NetworkInterfaces:
        - GroupSet:
            - !Ref LinuxSecurityGroup
          #AssociatePublicIpAddress: 'true'
          DeviceIndex: '0' 
          #DeleteOnTermination: 'true'
          SubnetId: !Ref Subnet
          PrivateIpAddress: 10.0.0.25
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update && \
            apt-get install -y \
              python \
              nmap \
              vim \
              git \
              wget \
              python3-dev && \
              apache2 && \
              wget https://raw.githubusercontent.com/daniellcurto/Project2/main/Project2-3/index-serv2.html?token=AQXGFYBDG7LD4J42ZJAJ5227Z75SM /home/ubuntu/ && \
              cp index-serv2.html /var/wwww/html/index.html && \          
            reboot