AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cloud configuration file for CEG 3120.  This template will build two Ubuntu servers per project package needs.
Parameters:
  UbuntuInstanceType:
    Description: Ubuntu Server instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: ' The IP address range that can be used to access the EC2 instance'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    # could restrict to home (note this is just SSH)
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings:
  AWSInstanceType2Arch:  # Supported architectures (x64bit only)
    t2.micro:
      Arch: HVM64
  AWSRegionUbuntu: # AMI for Ubuntu server in each supported region 
    us-east-1:   # N. Virginia
      PV64: NOT_SUPPORTED
      #TODO: is this the AMI we want?
      HVM64: ami-06c1d7addb12a814e
      HVMG2: NOT_SUPPORTED
    us-east-2:   # Ohio
      PV64: NOT_SUPPORTED
      HVM64: NOT_SUPPORTED
      HVMG2: NOT_SUPPORTED
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG 3120 VPC
  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG 3120 VPC
  # Have not messed with route tables / gateways before.
  # Look to see if anything unique, else move to next
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
  Route:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  SubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable
  # will also have 2 servers, keeping naming convention here
  Ubuntu1IPAddress:
    Type: 'AWS::EC2::EIP'
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      InstanceId: !Ref Ubuntu1Instance
  #Ubuntu2IPAddress:
  #  Type: 'AWS::EC2::EIP'
  #  DependsOn: AttachGateway
  #  Properties:
  #    Domain: vpc
  #    InstanceId: !Ref Ubuntu2Instance
  #WS19IPAddress:
  #  Type: 'AWS::EC2::EIP'
  #  DependsOn: AttachGateway
  #  Properties:
  #    Domain: vpc
  #    InstanceId: !Ref WS19Instance
  # TODO: Setup the security groups needed by our machines
  # SSH, LDAP, HTTP, HTTPS
  LinuxSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable SSH access via port 22 and open ports 1025 through 2048.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          # May be wise to go back to top where SSHLocation "variable" was made
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          # TODO: only leave ones we need.  What submet is this?
          CidrIp: 130.108.0.0/16  # WSU CIDR
        - IpProtocol: tcp
          FromPort: '1025'
          ToPort: '2048'
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: '1025'
          ToPort: '2048'
          CidrIp: 130.108.0.0/16  # WSU CIDR
        - IpProtocol: -1
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: 10.0.0.0/16
  Ubuntu1Instance:
    Type: 'AWS::EC2::Instance'
    DependsOn: AttachGateway
    Properties:
      ImageId: !FindInMap 
        - AWSRegionUbuntu
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref UbuntuInstanceType
          - Arch
      InstanceType: !Ref UbuntuInstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG 3400 Ubuntu 1
      NetworkInterfaces:
        - GroupSet:
            - !Ref LinuxSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref Subnet
          PrivateIpAddress: 10.0.0.20
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update && \
            # reference web solution here to get a silent install working
            apt-get install -y \
              python \
              nmap \
              vim \
              git \
              wget \
              python3-dev \
              ldap-utils && \
              haproxy && \
            
            # settings for HAProxy
            echo '"frontend http_front", "'\t'bind *:80", "'\t'stats uri /haproxy?stats", "'\t'default_backend http_back","backend http_back","'\t'balance roundrobin","'\t'server Ubuntu2Instance 10.0.0.20:80 check", "'\t'server Ubuntu3Instance 10.0.0.25:80 check", "backend blog_back", "'\t'server Ubuntu2Instance 10.0.0.20:80 check", "'\t'server Ubuntu3Instance 10.0.0.25:80"' > /etc/haproxy/haproxy.cfg && \
            echo "OMG this worked" >> /home/ubuntu/hello.txt && \
            echo "Hello World" >> /etc/skel/default.txt && \ 
            echo "open-server MIIEowIBAAKCAQEAgEX0taT8+pLsq2KEA5nqyGMF07JsyMzgr2KkNy5wZFhZx6vQt+mjaxcwNXB1Q1uWchzwtu1PsW3ZLxdO4W4DnnCZ9qOKvW9cETJYh6s1eQgnHw1qqBF5ewz9BSXtJmtTCxi+MecJCyMCPB4+UAI7hE6aEGaEhk+AnuM71hxM5Q8Zlwa6k/rgHAedyKcNlFsG3hxJxNiN+jdQrLxmi5SLtjFvND6uXXwWF5hQ00Ljf+iKrMicAGdcv7LECWi2lDLHiTPUotyCY4fASA7jJMCe24h6eXA2U4DGnfvofeCjKHUU52C/C1Ebo7OQu1+Jx+dNB+Z8+q11srXA+MUe87dR9QIDAQABAoIBAH61m+861XMoY4VAwatVBamAt6bQ38jTKTfWtuSTiQ52f+lPfdPOhVEqDMMdHZi2Bj0e/WGVtl1MZ3evDIp+xDBkhpIuJsTOFiIem3kY1K+EMDDqbesrp9a3k9DcEBEdf2C8xlRBJpvLr093iJI8QlKF2oZM3qhWLHXHfboZJpQ1GVlT1hfJ4FokLZGub4Vl63zx/wuYEmS/wX5QHrfYxioNXLIZdJBy3hXVnwP+fN39Tatgz3OdoBkpHo2zt41IliKHB6agmho0yLhFIgFGb+lxW02CJS2YkEMaREXMijCD+gRoryeawlXV4opiq2phDSROqLQbNT+5D3LbWV5lbUECgYEAwuu4PUTvgbpz/ti4SNfcVdlMNsFcutZoy8EphkQohF4qre7rcJHtA/tRM/ONY71qs4eh1bYg5KcNWeqr4Nipj72ZI6dBIkNxrOPO2xSldWmu7zopBsdJzlQWDSsnlM0IRnfkjQqLQJS+suqWpr/z8RTmHVL6zBlPr0ZiZYhFItkCgYEAqHfc8fMCgqCLX4RhgTAZnQ22VMbj01ed3whnIODSt24YBFTnp8P8Bzeeotm5Vt6NIytz7/3XIVFa+FlFBP3Zy40SmpgpIUVZWCeK8Uy9uwO9CaRo/Dh6NAJkboFz6NNgjbVVOPQmmK1wq1s5N2HXGFLXUq597d1DTijxfjsy/n0CgYEAvWaQyrAuTg8f4TUytE1T4vNXtCjlcwMeJ0aVk8qs2BosPIBYtDSHawQMHn/9Fjqa8MHNRj1H7wZH2eRGiR/eezaPFG7Twnhof8eIW6bPM6yyd/A6p0SEegGIv9j8CAHGlbqwEUB6mREvz+hU5MjGP66//yR/YE0D+dtZhzEHhNkCgYAObmYg275FTldiEUcA+AvZpkkOLhNqEUFWz7N134xtZiLsjBFkD6fRPnR6Ysg7psjUUG6YCliZZAy05YDCErTLeQQ09f/f977VjF2cmgROtt1ErC7KHFRrjCDqTnCNaz4EJZptTIzZ21GhfCkEk38HeGE1lfj3nVKcqWk2dP/DSQKBgGQy4iNnVcPS6elMncDzubiMFx8a4wwQc0Z+UMBMUpYL3sTz7i++U8b/QnzcNw/Hxn95qrliH382IIDPh+PKfr7BVJlP2YsMKd6EScXfA7l6sIwzxg269NlY7smJwFFJnNemWO3QImqVdid8FjaPM0rxqeHlIbI4dEccvZGVerb0== server-keys" >> /home/ubuntu/.ssh/authorized_keys && \
            reboot
            
  Ubuntu2Instance:
    Type: 'AWS::EC2::Instance'
    DependsOn: AttachGateway
    Properties:
      ImageId: !FindInMap 
        - AWSRegionUbuntu
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref UbuntuInstanceType
          - Arch
      InstanceType: !Ref UbuntuInstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG 3400 Ubuntu 2
      NetworkInterfaces:
        - GroupSet:
            - !Ref LinuxSecurityGroup
          #AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          #DeleteOnTermination: 'true'
          SubnetId: !Ref Subnet
          PrivateIpAddress: 10.0.0.20
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update && \
            apt-get install -y \
              python \
              nmap \
              vim \
              git \
              wget \
              python3-dev && \
              apache2 && \
              wget https://raw.githubusercontent.com/daniellcurto/Project2/main/Project2-3/index-serv1.html?token=AQXGFYBJML4JATWD7XQH6GC7Z75NW /home/ubuntu/ && \
              cp index-serv1.html /var/wwww/html/index.html && \
            reboot

  Ubuntu3Instance:
    Type: 'AWS::EC2::Instance'
    DependsOn: AttachGateway
    Properties:
      ImageId: !FindInMap 
        - AWSRegionUbuntu
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref UbuntuInstanceType
          - Arch
      InstanceType: !Ref UbuntuInstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Name
          Value: CEG 3400 Ubuntu 3
      NetworkInterfaces:
        - GroupSet:
            - !Ref LinuxSecurityGroup
          #AssociatePublicIpAddress: 'true'
          DeviceIndex: '0' 
          #DeleteOnTermination: 'true'
          SubnetId: !Ref Subnet
          PrivateIpAddress: 10.0.0.25
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update && \
            apt-get install -y \
              python \
              nmap \
              vim \
              git \
              wget \
              python3-dev && \
              apache2 && \
              wget https://raw.githubusercontent.com/daniellcurto/Project2/main/Project2-3/index-serv2.html?token=AQXGFYBDG7LD4J42ZJAJ5227Z75SM /home/ubuntu/ && \
              cp index-serv2.html /var/wwww/html/index.html && \          
            reboot